### ISSUE TITLE
Move to `tink.http.Client`?

### ISSUE THREAD

**Issue by back2dos** [kevinresol/tink_http_fetch#1]
Since `Client` is an abstract, it might also have a static `fetch` method. Thoughts?

**Comment by kevinresol** [comment]
Sure, why not? 
That would be more convenient too (no need to include extra library)

**Comment by kevinresol** [comment]
btw, I think [this](https://github.com/kevinresol/tink_http_fetch/blob/8b3da88/src/tink/http/Fetch.hx#L112-L122) should also be included in tink_http as some sort of utility type.
